### ISSUE TITLE
Host from within game: Pressing Shift+Esc segfaults

### ISSUE THREAD

**Issue by SimonN** [SimonN/lix-unstable#7]
Lix 0.9.44
Host game yourself.
Open 2nd instance of Lix and connect to yourself.
Select and start a map.
During play, kill the 2nd instance of Lix with Shift+Esc.
Kill the 1st instance of Lix with Shift+Esc.
The 1st instance of Lix will now crash with the following backtrace:

```
  Thread 1 "lix" received signal SIGSEGV, Segmentation fault.
  0x0000555555c2d82d in _d_interface_cast ()
  (gdb) bt
  #0  0x0000555555c2d82d in _d_interface_cast ()
  #1  0x0000555555a9ad90 in object.destroy!(true, net.server.suite.Suite).destroy(net.server.suite.Suite) (obj=0x7ffff4f176d0)
      at /usr/include/dlang/dmd/object.d:4451
  #2  0x0000555555bce4a1 in net.server.hotel.Hotel.dispose() (this=...)
      at src/server/src/hotel.d:62
  #3  0x0000555555bcf970 in net.server.server.NetServer.~this() (
      this=0x7ffff55d3000) at src/server/src/server.d:68
  #4  0x0000555555bd09a5 in net.server.server.NetServer.__aggrDtor() (
      this=0x7ffff55d3000) at src/server/src/server.d:62
  #5  0x0000555555c2fbdb in rt_finalize2 ()
  #6  0x0000555555c997af in rt_finalizeFromGC ()
  #7  0x0000555555c909fb in core.internal.gc.impl.conservative.gc.Gcx.sweep() ()
  #8  0x0000555555c921e4 in core.internal.gc.impl.conservative.gc.Gcx.fullcollect(bool, bool, bool) ()
  #9  0x0000555555c96a40 in core.internal.gc.impl.conservative.gc.ConservativeGC.runLocked!(core.internal.gc.impl.conservative.gc.ConservativeGC.fullCollectNoStack().go(core.internal.gc.impl.conservative.gc.Gcx*), core.internal.gc.impl.conservative.gc.Gcx*).runLocked(ref core.internal.gc.impl.conservative.gc.Gcx*) ()
  #10 0x0000555555c8ec24 in core.internal.gc.impl.conservative.gc.ConservativeGC.fullCollectNoStack() ()
  #11 0x0000555555c8ebb2 in core.internal.gc.impl.conservative.gc.ConservativeGC.collectNoStack() ()
```

**Comment by SimonN** [comment]
Doesn't happen anymore in 0.10.9. Most likely. I've fixed this long before 0.10 was ready, and merely didn't remember to close this bug.
